version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - echo $AWS_ACCOUNT_ID
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION > ecr_login_password.txt
      - cat ecr_login_password.txt | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd docker  # Change to the directory containing the Dockerfile
      - docker build -t my-image .
      - docker images  # List Docker images to verify build
      - docker tag my-image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker images  # List Docker images to verify tagging
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo Docker image pushed to ECR
env:
  variables:
    AWS_ACCOUNT_ID: "641131565149"
    AWS_DEFAULT_REGION: "ap-northeast-1"
    IMAGE_REPO_NAME: "hochituong7/nextjs-tools"